jokesapp/urls.py
from django.urls import path
from . import views

app_name = "jokesapp"

urlpatterns = [
    # index pages (Joke and category)
    path('' , views.Index.as_view() , name="Index"),
    path('categories', views.IndexCategory.as_view() , name="categories"),
    # Path Joke
    path('create', views.create , name="create"),
    path('post_create' , views.post_create , name="post_create"),
    path('<int:joke_id>/update' , views.update , name="update"),
    path('<int:joke_id>/post_update' , views.post_update , name="post_update"),
    path('<int:joke_id>/delete' , views.delete , name="delete"),
    # Jokes in corbeille
    path('jokes_deleted' , views.IndexJokeRemove.as_view() , name="joke_deleted"),
    # Category
    path('create_cat', views.create_cat , name="create_cat"),
    path('post_create_cat', views.post_create_cat , name="post_create_cat"),
    path('<int:cat_id>/update_cat', views.update_cat , name="update_cat"),
    path('<int:cat_id>/post_update_cat', views.post_update_cat , name="post_update_cat"),
    path('<int:cat_id>/delete_cat', views.delete_cat , name="delete_cat"),
    # Categories in corbeille
    path('categories_deleted' , views.IndexCategoryRemove.as_view() , name="categories_deleted"),
    # Joke by categories
    path('<int:cat_id>/display_joke_by_category' , views.display_joke_by_category, name="display_joke_by_category"),
    # remove element - path
    path('<int:cat_id>/remove_cat', views.remove_cat , name="remove_cat"),
    path('<int:joke_id>/remove_joke', views.remove_joke , name="remove_joke"),
    # restore element - path
    path('<int:cat_id>/restore_cat', views.restore_cat , name="restore_cat"),
    path('<int:joke_id>/restore_joke', views.restore_joke , name="restore_joke"),
    # search a joke by word
    path('search_joke' , views.search_joke_by_word, name="search_joke")
    
]

jokesproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jokes/' , include('jokesapp.urls'))
]

jokesapp/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Category(models.Model):
    
    libelle = models.CharField(max_length=180)
    view = models.BooleanField(default=True)
    
    def __str__(self):
        return self.libelle
    

class Joke(models.Model):
    
    category = models.ForeignKey(Category , on_delete=models.CASCADE)
    question = models.CharField(max_length=300)
    answer = models.CharField(max_length=150)
    date_pub = models.DateTimeField("Date pub")
    view = models.BooleanField(default=True)
    
    def __str__(self) -> str:
        return self.question
    
    def is_recent(self):
        time = timezone.now()
        return time - datetime.timedelta(days=1) <= self.date_pub <= time

jokesapp/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, get_list_or_404 , get_object_or_404
from .models import Joke , Category
from django.views import generic
from django.urls import reverse
from django.utils import timezone

# Create your views here.
class Index(generic.ListView):
    
    template_name = "jokesapp/index.html"
    context_object_name = "jokes"
    
    def get_queryset(self):
        return Joke.objects.all().order_by('-date_pub').filter(view = True);
    
# display all joke in corbeille
class IndexJokeRemove(generic.ListView):
    
    template_name = "jokesapp/jokes_remove.html"
    context_object_name = "jokes"
    
    def get_queryset(self):
        return Joke.objects.all().order_by('-date_pub').filter(view = False);


# views create jokes page
def create(request):
    # we need to send list of category in this page
    list_cat = Category.objects.all();
    print(list_cat)
    return render(request , "jokesapp/create.html" , {"categories":list_cat})

# post method for create jokes page 
def post_create(request):
    # print(request.POST.get("category"))
    # print(request.POST.get("question"))
    # print(request.POST.get("answer"))
    # print(timezone.now())
    
    # get category eq to cat
    cat = Category.objects.get(id = request.POST.get("category"))
    
    # jokes , created = Joke.objects.get_or_create(category=request.POST.get("category") , question=request.POST.get("question") , answer=request.POST.get("answer") , date_pub=timezone.now())
    j = Joke(category=cat , question=request.POST.get("question") , answer=request.POST.get("answer") , date_pub=timezone.now())
    j.save()
    
    return HttpResponseRedirect(reverse("jokesapp:Index" , args=()))


def update(request , joke_id):
    # get joke correspond to id 
    j = Joke.objects.get(id = joke_id)
    print(j.category.id)
    
    list_cat = Category.objects.all();
    print(list_cat)
    return render(request , "jokesapp/update.html" , {"categories":list_cat , "joke":j})

def post_update(request , joke_id):
    # get joke which correspond to id
    j = Joke.objects.get(id = joke_id)
    
    # value of category
    cat = Category.objects.get(id = request.POST.get("category"))
    
    # get joke
    j = get_object_or_404(Joke , id=joke_id)
    
    j.category = cat
    j.question = request.POST.get("question")
    j.answer = request.POST.get("answer")
    
    # save all changes
    j.save()
    
    return HttpResponseRedirect(reverse("jokesapp:Index" , args=()))


def delete(request , joke_id):
    # get joke 
    j = Joke.objects.get(id = joke_id)
    # j = get_object_or_404(Joke , id=joke_id)
    print(j.question)
    j.delete()
    # dont need to add save()
    
    # redirection
    return HttpResponseRedirect(reverse("jokesapp:Index" , args=()))

# Send Joke in corbeille Joke
def remove_joke(request , joke_id):
    # get joke 
    j = Joke.objects.get(id = joke_id)
    # j = get_object_or_404(Joke , id=joke_id)
    print(j.question)
    j.view = False
    j.save()
    # dont need to add save()
    
    # redirection
    return HttpResponseRedirect(reverse("jokesapp:Index" , args=()))

def restore_joke(request , joke_id):
    # get joke 
    j = Joke.objects.get(id = joke_id)
    # j = get_object_or_404(Joke , id=joke_id)
    # print(j.question)
    j.view = True
    j.save()
    # redirection
    return HttpResponseRedirect(reverse("jokesapp:Index" , args=()))


# Categories views
class IndexCategory(generic.ListView):
    template_name = "jokesapp/lists_categories.html"
    context_object_name = "categories"
    
    def get_queryset(self):
        return Category.objects.all().order_by("libelle").filter(view = True)
    

# display all categories in corbeille
class IndexCategoryRemove(generic.ListView):
    template_name = "jokesapp/categories_remove.html"
    context_object_name = "categories"
    
    def get_queryset(self):
        return Category.objects.all().order_by("libelle").filter(view = False)

def create_cat(request):
    return render(request , "jokesapp/create_category.html")

def post_create_cat(request):
    # get libelle post
    c = Category.objects.create(libelle = request.POST.get("libelle"))
    c.save()
    return HttpResponseRedirect(reverse("jokesapp:categories" , args=()))

def update_cat(request , cat_id):
    # send category which correspond to id
    cat = Category.objects.get(id = cat_id)
    return render(request , "jokesapp/update_category.html" , {"category":cat})

def post_update_cat(request , cat_id):
    # get category which correspond to id
    cat = Category.objects.get(id = cat_id)
    cat.libelle = request.POST.get("libelle")
    cat.save()
    return HttpResponseRedirect(reverse("jokesapp:categories" , args=()))


def delete_cat(request , cat_id):
    # /get category which corrspond to cat_id
    c = Category.objects.get(id = cat_id)
    c.delete()
    
    return HttpResponseRedirect(reverse("jokesapp:categories" , args=()))

# Send category in corbeille
def remove_cat(request , cat_id):
    # /get category which corrspond to cat_id
    c = Category.objects.get(id = cat_id)
    c.view = False
    c.save()
    
    return HttpResponseRedirect(reverse("jokesapp:categories" , args=()))

# restore catgeory in corbeille
def restore_cat(request , cat_id):
     # /get category which corrspond to cat_id
    c = Category.objects.get(id = cat_id)
    c.view = True
    c.save()
    
    return HttpResponseRedirect(reverse("jokesapp:categories" , args=()))

# views joke by category
def display_joke_by_category(request , cat_id):
    cat = Category.objects.get(id = cat_id)
    joke_for_cat = get_list_or_404(Joke , category = cat)
    
    print(joke_for_cat)
    
    return render(request , "jokesapp/list_joke_by_category.html" , {"jokes":joke_for_cat , "category":cat})


# Search a joke , views result.
def search_joke_by_word(request):
    # get word params 
    word = request.GET.get("word")
    print("Word is:",word)
    jokes = Joke.objects.filter(question__contains=word)
    # pri
    # redirection to result
    return render(request , "jokesapp/search_joke_by_word.html" , {"jokes":jokes , "query":word})

jokesapp/templates/jokesapp/categories_remove.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'jokesapp/lists.css' %}"/>
    <title>Categories in "corbeille"</title>
</head>
<body>
    
    <h1>Lists of categories deleted</h1>
    <!-- <div>
        <a href="{% url 'jokesapp:create_cat' %}">Add a category</a>
    </div> -->

    <div>
        {% if categories.count %}
            <table class="table table-hover table-bordered border-dark">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Category</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cat in categories %}
                        <tr>
                            <td>{{cat.id}}</td>
                            <td>{{cat.libelle}}</td>
                            <td>
                                <a class="btn btn-primary"  href="{% url 'jokesapp:restore_cat' cat.id %}">Restore</a> - <a class="btn btn-danger"  href="{% url 'jokesapp:delete_cat' cat.id %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div>No categories deleted</div>
        {% endif %}
    </div>


</body>
</html>

jokesapp/templates/jokesapp/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'jokesapp/page_form.css' %}"/>
    
    <title>Create a joke</title>
</head>
<body>
    
    <div class="form">
        <h1 style="text-align:center;">Add a joke</h1>
        <form action="{% url 'jokesapp:post_create' %}" method="post">
            {% csrf_token %}
            <div class='input-bloc'>
                <label for="category">Category</label>
                <select name="category" id="category">
                    {% for cat in categories %}
                        <option value={{cat.id}}>{{cat.libelle}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class='input-bloc'>
                <label for="question">Question : </label>
                <input type="text" name="question" id="question">
            </div>
            <div class='input-bloc'>
                <label for="answer">Answer : </label>
                <input type="text" name="answer" id="answer">
            </div>
            <div class='input-bloc'>
                <button type="submit" class="btn btn-dark">Save</button>
            </div>
        </form>
        <a style="text-align:center;" href="{% url 'jokesapp:Index' %}">Go home</a>
    </div>
    
</body>
</html>

jokesapp/templates/jokesapp/create_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'jokesapp/page_form.css' %}"/>

    <title>Create a category</title>
</head>
<body>
    
    <div class="form">
        <h1 style="text-align:center;">Add a category</h1>
        <form action="{% url 'jokesapp:post_create_cat' %}" method="post">
            {% csrf_token %}
            <div class='input-bloc'>
                <label for="category">Category Name : </label>
                <input type="text" name="libelle" id="libell">
            </div>
            <div class='input-bloc'>
                <input type="submit" class="btn btn-dark" value="Save">
            </div>
        </form>
        <a style="text-align:center;" href="{% url 'jokesapp:Index' %}">Go home</a>
    </div>
    
</body>
</html>

jokesapp/templates/jokesapp/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

jokesapp/templates/jokesapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'jokesapp/index.css' %}" />
    <title>Document</title>
</head>
<body>
    
    <!-- header -->
    <div style="display: flex;justify-content: space-between;align-items: center;border-bottom:solid;margin:15px;">
        <h1>Lists of jokes</h1>
        <form method="get" action="{% url 'jokesapp:search_joke' %}">
            <div style="display:flex;flex-direction: column;">
                <label for="word">Search by joke :</label>
                <input 
                    style="height: 40px;border-radius: 3px;border: solid .5px;outline: none;"
                    type="search" name="word" id="word" placeholder="Search a joke..."
                >
            </div>
        </form>
    </div>
    
    <div style="display: flex; gap:100px;justify-content: center; margin:20px;">
        <a class="link" href="{% url 'jokesapp:categories' %}">Lists of Categories</a>
        <a class="link" href="{% url 'jokesapp:create' %}">Add a joke</a>
        <a class="link" href="{% url 'jokesapp:joke_deleted' %}">Jokes in corbeille</a>
    </div>
    <div class="container">
        <div class="row g-2" >
            {% for joke in jokes %}
                <div class="col-4 border border-dark flex d-flex flex-column align-items-center">
                    {{joke.question}}
                    - {{joke.category}} 
                    <!-- links -->
                    <div> <a href="{% url 'jokesapp:update' joke.id %}">Update</a> - <a href="{% url 'jokesapp:remove_joke' joke.id %}">Delete</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

</body>
</html>

jokesapp/templates/jokesapp/jokes_remove.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'jokesapp/lists.css' %}"/>
    <title>Jokes in "corbeille"</title>
</head>
<body>
    
    <h1>Lists of jokes deleted</h1>

    <div>
        {% if jokes %}
            <table class="table table-hover table-bordered border-dark">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Joke</th>
                        <th>Answer</th>
                        <th>Category</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody>
                    {% for joke in jokes %}
                        <tr>
                            <td>{{joke.id}}</td>
                            <td>{{joke.question}}</td>
                            <td>
                                {{joke.answer}}
                            </td>
                            <td>
                                {{joke.category}}
                            </td>
                            <td>
                                {% comment %} <ahref="{% url 'jokesapp:update_cat' cat.id %}">Update</a> - <ahref="{% url 'jokesapp:remove_cat' cat.id %}">Delete</a> {% endcomment %}
                                <a class="btn btn-primary"  href="{% url 'jokesapp:restore_joke' joke.id %}">Restore</a> - <a class="btn btn-danger"  href="{% url 'jokesapp:delete' joke.id %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div>No jokes deleted</div>
        {% endif %}
    </div>

</body>
</html>

jokesapp/templates/jokesapp/list_joke_by_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Jokes for : {{cat.libelle}} </h1>
    <div>
        <a href="{% url 'jokesapp:categories' %}">Return</a>
    </div>
    <div>
        <ul>
            {% for joke in jokes %}
                <li>
                    {{joke.question}}
                    ({{joke.category}}) - <a href="{% url 'jokesapp:update' joke.id %}">Update</a> - <a href="{% url 'jokesapp:delete' joke.id %}">Delete</a>
                </li>
            {% endfor %}
        </ul>
    </div>

</body>
</html>

jokesapp/templates/jokesapp/lists_categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'jokesapp/lists.css' %}"/>
    <title>Document</title>
</head>
<body>
    
    {% comment %} header {% endcomment %}
    <div class="links">
        <h1>Lists of categories</h1>
        <div style="display: flex; gap:15px;">
            <a class="link" href="{% url 'jokesapp:create_cat' %}">Add a category</a>
            <a class="link" href="{% url 'jokesapp:categories_deleted' %}">Categories in corbeille</a>
        </div>
    </div>

    <div style="text-align:center;">
        <table class="table table-hover table-bordered border-dark">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Category</th>
                    <th>Numbers of jokes</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
                {% for cat in categories %}
                    <tr>
                        <td>{{cat.id}}</td>
                        <td>{{cat.libelle}}</td>
                        <td>
                            {% if cat.joke_set.all.count %}
                                <a href="{% url 'jokesapp:display_joke_by_category' cat.id %}">({{cat.joke_set.all.count}} Jokes)</a>
                                {% else %}(0 Jokes)
                            {% endif %} 
                        </td>
                        <td>
                            <a class="btn btn-dark" href="{% url 'jokesapp:update_cat' cat.id %}">Update</a> - <a class="btn btn-danger" href="{% url 'jokesapp:remove_cat' cat.id %}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'jokesapp:Index' %}">Go to home page</a>
    </div>

</body>
</html>

jokesapp/templates/jokesapp/search_joke_by_word.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'jokesapp/index.css' %}"/>
    <title>Document</title>
</head>
<body>
    
    <!-- header -->
    <div style="display: flex;justify-content: space-between;align-items: center;border-bottom:solid;margin:15px;">
        <h1>Lists of jokes</h1>
        <form method="get" action="{% url 'jokesapp:search_joke' %}">
            {% csrf_token %}
            <div style="display:flex;flex-direction: column;">
                <label for="word">Search by joke :</label>
                <input 
                    style="height: 40px;border-radius: 3px;border: solid .5px;outline: none;"
                    type="search" name="word" id="word" placeholder="Search a joke..."
                >
            </div>
        </form>
    </div>

    {% if jokes %}
        <div style="display:flex; justify-content:center; align-items:center;height:60vh;margin:100px;">
            <table class="table table-hover table-bordered border-dark text-center">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Joke</th>
                        <th>Answer</th>
                        <th>Category</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody>
                    {% for joke in jokes %}
                        <tr>
                            <td>{{joke.id}}</td>
                            <td>{{joke.question}}</td>
                            <td>
                                {{joke.answer}}
                            </td>
                            <td>
                                {{joke.category}}
                            </td>
                            <td>
                                {% comment %} <ahref="{% url 'jokesapp:update_cat' cat.id %}">Update</a> - <ahref="{% url 'jokesapp:remove_cat' cat.id %}">Delete</a> {% endcomment %}
                                <a class="btn btn-primary"  href="{% url 'jokesapp:update' joke.id %}">Update</a> - <a class="btn btn-danger"  href="{% url 'jokesapp:remove_joke' joke.id %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div style="display:flex;flex-direction:column;align-items:center; justify-content:center;font-weight:bold;font-size:20px;margin-top:100px;">
            <p>No jokes deleted</p>
            <a href="{% url 'jokesapp:Index' %}">Return to home page</a>
        </div>
    {% endif %}    

</body>
</html>

jokesapp/templates/jokesapp/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'jokesapp/page_form.css' %}"/>
    <title>Document</title>
</head>
<body>
    
    <div class="form">
        <h1 style="text-align: center;">Add a joke</h1>
        <form action="{% url 'jokesapp:post_update' joke.id %}" method="post">
            {% csrf_token %}
            <div class="input-bloc">
                <label for="category">Category</label>
                <select name="category" id="category">
                    {% for cat in categories %}
                        {% if cat.id == joke.category.id %}
                            <option valuwe="{{joke.category.id}}" selected>{{cat.libelle}}</option>
                        {% else %}
                            <option value="{{joke.category.id}}">{{cat.libelle}}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="input-bloc">
                <label for="question">Question : </label>
                <input type="text" name="question" id="question" value="{{joke.question}}">
            </div>
            <div class="input-bloc">
                <label for="answer">Answer : </label>
                <input type="text" name="answer" id="answer" value="{{joke.answer}}">
            </div>
            <div class="input-bloc">
                <input type="submit" class="btn btn-dark" value="Update">
            </div>
        </form>
        <a style="text-align: center;" href="{% url 'jokesapp:Index' %}">Go home</a>
    </div>
    
</body>
</html>